from typing import TypedDict, List, Dict, Any, Annotated
import operator

class AgentState(TypedDict):
    """
    Strongly typed state object representing the full clinical and operational context
    passed between nodes in the LangGraph agent workflow.
    """
    query: str                                      # User Query
    history: List[Dict[str, str]]                   # Conversation History
    retrieved_hospital_context: List[str]           # Retrieved Hospital Context
    retrieved_patient_context: List[str]             # Retrieved Patient Context (chunks from patient FAISS)
    similar_patient_results: List[Dict[str, Any]]   # Similar Patient Results (clinical cases matching)
    current_patient_info: Dict[str, Any]            # Current Patient Information (structured from SQLite)
    tool_outputs: Annotated[List[Dict[str, Any]], operator.add]  # Aggregated tool execution outputs
    final_context: str                              # Formatted final context sent to the LLM
    final_response: str                             # Response generated by the LLM
    sources_used: List[str]                         # Sources/citations (files, patient IDs, SQLite tables)
    current_tool_execution: List[Dict[str, Any]]    # Active list of tool calls scheduled to be executed next
    api_key: str                                    # User-supplied Groq API Key
